### ISSUE TITLE
False positive on fn returning vector?

### ISSUE THREAD

**Issue by markusschlegel** [jonase/kibit#220] opened 2018-10-30 15:32 UTC
I got

```
Consider using:
  :embed
instead of:
  (fn [sub] [:embed sub])
```

which seems like an odd suggestion to me.

**Comment by arrdem** [comment] 2018-10-30 22:39
This is sadly a duplicate of https://github.com/jonase/kibit/issues/49

**Closed** 2018-10-31 01:11 UTC
Labels: duplicate
